# Generated by Django 4.0.6 on 2022-07-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_collection_created_at_collection_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
