# Generated by Django 4.0.6 on 2022-08-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product_default.png', null=True, upload_to='product_pics'),
        ),
    ]
