# Generated by Django 4.0.6 on 2022-08-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_userfollowing_delete_followerscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created_at']},
        ),
    ]
