# Generated by Django 4.0.6 on 2022-08-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comment_dislikes_comment_likes_comment_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
