# Generated by Django 4.0.6 on 2022-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_image',
            field=models.ImageField(blank=True, default='post_image_default.png', null=True, upload_to='comments_pics'),
        ),
    ]
