# Generated by Django 4.0.6 on 2022-08-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_comment_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_image',
            new_name='comment_image',
        ),
    ]
