# Generated by Django 4.0.6 on 2022-08-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
